### ISSUE TITLE
loading momentjs too many times

### ISSUE THREAD

**Issue by ArthurJahn** [saeidzebardast/moment-js#1]
I've been playing with your component and found out that it loads `momentjs` lib every time its added on html.
Would it be a good idea to load it with [iron-jsonp-library](https://elements.polymer-project.org/elements/iron-jsonp-library) instead of directly inside a `script` tag?

I'm asking this because my global `locale` setting is always reset when I use the component. I'd like to make this contribution if you agree with it.

**Comment by saeidzebardast** [comment]
Dear Arthur,

I've imported external library same as the Polymer way. Check the following pages:
- [Polymer element with javascript dependencies](http://stackoverflow.com/questions/22135095/polymer-element-with-javascript-dependencies)
- [Enforce a folder structure](https://www.tjvantoll.com/2014/08/12/the-problem-with-using-html-imports-for-dependency-management/)

Could you tell me more about your issue?

**Comment by ArthurJahn** [comment]
the `moment-js` component is meant to be used many times on same app, but configuring global `locale` doesn't work if you add many times the component because it loads the `moment.js` lib every time. 

some components can be used the same way, like `google-map`, that is used many times on same application but just loads the `google-map-api` once, when the first component is added to DOM. 

The google maps component uses the jsonp polymer component to load the map api instead of loading a script tag every time the map is used. Guess that doing the same way, you can add global configs to `moment` by passing `attrs` values to your component, like 

```
<moment-js global-locale="pt-br"></moment-js>
```

currently this is not supported, since that when you add another component, this global config will be lost because moment will be loaded again.

This is just an idea, I've started doing this [here](https://github.com/ArthurJahn/moment-js/commit/56f878daa628314f527d4f165f0d169d7f0fb93c) if you want to take a look at it an give me a feedback. 

thanks!

**Comment by saeidzebardast** [comment]
I've got it. Thank for the detailed explanation. I checked you fork and it looks good. But there is an issue for using CDN. if the web app does not access to the internet, it could not load moment library. e.g. it's behind the firewall  or the internet connection is lost.
Could you replace the CDN with the local moment library in bower_components?

**Comment by ArthurJahn** [comment]
That cannot be done. I've tried to replace here but bower custom directory configuration would make the load fail. Guess that this is a [big issue](https://www.tjvantoll.com/2014/08/12/the-problem-with-using-html-imports-for-dependency-management/) that the community is still trying to solve. Actually, if we are going to deal with this, maybe we could back to the script tag, but we should verify if moment is not loaded before inserting the tag. What do you think?

**Comment by saeidzebardast** [comment]
I think that's the best way now. We could check moment before loading it
using script tag. Could you update your fork for this issue?

**Comment by ArthurJahn** [comment]
yes, I'm gonna do this.

**Comment by saeidzebardast** [comment]
Thanks.

**Comment by masonlouchart** [comment]
There is some news? I would like to contribute for the locale setting but this one has to be done first. Please @ArthurJahn, could you reuse the script tag as mentioned above and propose a PR?

**Comment by ArthurJahn** [comment]
The best way I've found for doing this is [here](https://github.com/ArthurJahn/moment-js/commit/d6648679d23622c10464374e257cafa81ad0c47f). Check that out and give me some feedback. 
Sorry for making you, guys wait, I'm very busy this days.

**Comment by masonlouchart** [comment]
I thought you had also kept [this code](https://github.com/ArthurJahn/moment-js/commit/56f878daa628314f527d4f165f0d169d7f0fb93c) with the event fired by moment-import. I think we can check both out and propose a nice PR. Thank you @ArthurJahn !

**Comment by masonlouchart** [comment]
In fact we can't just use the script tag for loading `momentjs`. The element has some properties and observers needing `momentjs` ready.  So, it must be loaded one time and before the element itself.

🚧 👷 🚧 
I'm working on a behavior but it's not really easy (because I can't delay the `ready` callback). If anyone has an idea...

**Comment by saeidzebardast** [comment]
@LM450N Could you share your code at your fork?

**Comment by masonlouchart** [comment]
@saeidzebardast Sure! Right after I'm back home and made a little clean up...of the code (this evening after work). 😉

**Comment by saeidzebardast** [comment]
Thanks
Mason Louchart notifications@github.com schrieb am Mi., 10. Aug. 2016 um
18:16:

**Comment by masonlouchart** [comment]
I've pushed [a branch](https://github.com/LM450N/moment-js/tree/momentjs-dependency-loading) with my last try. Please, read the commit message carefully (_TL;DR: this is not working yet_).

Moreover, [this thread](https://github.com/Polymer/polymer/issues/3845) is about a similar issue.

**Comment by saeidzebardast** [comment]
I've just finished the MomentImportBehavior. Unit tests need some changes. I'll push the new version after fixing unit tests.

**Comment by saeidzebardast** [comment]
@LM450N everything works fine but there is a problem in relative src path. In JS, paths are relative to displayed page. Check the following links:
http://stackoverflow.com/questions/2188218/relative-paths-in-javascript-in-an-external-file
http://stackoverflow.com/questions/1411627/javascript-src-path

**Comment by masonlouchart** [comment]
I should say my brain can't accept that the script tag doesn't work as inserting dynamically a script tag.

Why this is working

``` javascript
<script src="../moment/min/moment.min.js"></script>
```

but not this

``` javascript
var script = document.createElement('script');
script.src = '../moment/min/moment.min.js';
document.body.appendChild(script);
```

Maybe there is a workaround to do with the import tag of the element itself (`moment-js`). The purpose would be to get the URL to its root folder (in my case the _"bower_components"_) and use it to load `moment`. I guess if this kind of trick is possible, someone else might have already did it.

_PS: It could be cool if I could see your source code._ 😎

**Comment by saeidzebardast** [comment]
@LM450N I've pushed the change to a new branch https://github.com/saeidzebardast/moment-js/tree/momentjs-dependency-loading
You could run `polymer serve` and `polymer test` without seeing any errors. I'll search to find a way to fix the relative path issue.

**Comment by saeidzebardast** [comment]
@LM450N Thanks for the PR. I've merged it. The latest version (v0.5.0) contains the fix.
Now, we could work on #3 :smiley:
