### ISSUE TITLE
Question about observers implementation

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#11]
If you allow me, I have some questions about the way used for the implementation of the observers.
- Firstly, why use three times [the same observer on one property](https://github.com/saeidzebardast/moment-js/blob/master/moment-js.html#L178-L180) instead of one observer on three properties (like `_updateFormattedDateMoment(date, dateFormat, utc)`)?
- Secondly, why use an observer [without parameter](https://github.com/saeidzebardast/moment-js/blob/master/moment-js.html#L215) instead a computed property for `isValid`?
- Finally, why do you prefer use [observer without parameters](https://github.com/saeidzebardast/moment-js/blob/master/moment-js.html#L227-L244)? Is it a performance concern or readability?

Thank you for your answers and your help.

**Comment by saeidzebardast** [comment]
Thanks for asking the questions. It helps me to improve this element.
1. An observer with multiple properties is called if all of the properties were defined. e.g. if I use an observer like  `_updateFormattedDateMoment(date, dateFormat, utc)`, the `date`, `dateFormat` and `utc` should be not `undefined`.
2. Thanks for the suggestion :pray: . I'll try to replace it with a computed property.
3. It's not a performance concern. I just want to have readable code :smirk:

**Comment by masonlouchart** [comment]
Thank you for the answer.
1. That's why I couldn't make it work with parameters!  👊 😵 😴 🏥 
2. The computed property works, I already tried it. ✅ 
3. This point is subjective.

**Comment by saeidzebardast** [comment]
@LM450N Could you create a PR for changing the `isValid` to a computed property?

**Comment by saeidzebardast** [comment]
@LM450N Thanks for really quick PR.
