### ISSUE TITLE
Travis tests only Chrome

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#13]
Travis tests only Chrome, is it intentional?

<img width="1029" alt="capture d ecran 2016-08-03 a 22 15 13" src="https://cloud.githubusercontent.com/assets/2325091/17380563/03761e54-59c8-11e6-83d3-ea7769d1be78.png">

**Comment by saeidzebardast** [comment]
There is a problem in Selenium 9c39b43.
