### ISSUE TITLE
Observer called too much times.

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#15]
The fact to have three times the same observer on three properties triggers it more times than one observer on all of those three properties.
### Current state on the demo page

_(the observer is triggered 25 times)_
<img width="806" alt="capture d ecran 2016-08-07 a 14 15 11" src="https://cloud.githubusercontent.com/assets/2325091/17462636/8a3b7072-5cb3-11e6-98a7-3c84738d1fcb.png">
### By using an observer on the three properties

_(the observer is triggered 9 times)_
<img width="794" alt="capture d ecran 2016-08-07 a 15 11 12" src="https://cloud.githubusercontent.com/assets/2325091/17462643/c730ec28-5cb3-11e6-9619-4960253c4170.png">

**Comment by saeidzebardast** [comment]
@LM450N Thanks. But I think it's better to use a single observer to make sure all of the parameters are defined. I'm going to use debounce to prevent multiple executions.

**Comment by saeidzebardast** [comment]
Using debounce has some side effects. It seems that setting a default value for date and use single observer is the best approach now.
Could you update the PR and add a unit test for setting default date value?
