### ISSUE TITLE
ISO 8601 format

### ISSUE THREAD

**Issue by Boscop** [saeidzebardast/moment-js#19]
I want to parse a ISO 8601 date:
```html
<moment-js date="[[post.created_at]]" from-now="true"></moment-js>
```
I get a warning in the console from moment.js that parsing without format string is deprecated.
moment.js has support for special format constants, like `moment.ISO_8601`:
https://momentjs.com/docs/#/parsing/special-formats/
But when parsing a date with the moment element, `date-format` has to be string.

How can I pass `moment.ISO_8601` to the moment element?

**Comment by saeidzebardast** [comment]
`moment.ISO_8601` is a constant. You can't pass it.
![screen shot 1395-12-26 at 11 02 46](https://cloud.githubusercontent.com/assets/896271/23986220/50984b28-0a38-11e7-88b7-13f67545ba36.png)

However, you could pass same ISO format like `YYYY-MM-DDTHH:mm:ss.sssZ`.
