### ISSUE TITLE
Time doesn't update itself.

### ISSUE THREAD

**Issue by amanshu-kataria** [saeidzebardast/moment-js#29]
## Expected Outcome
The time should be updated every minute/second.

## Actual Outcome
The time doesn't update automatically.

**Comment by masonlouchart** [comment]
The browser does not refresh automatically the document every second so it's not the default behavior, this is not native.

But it could be a nice feature request!

**Comment by amanshu-kataria** [comment]
It would be really helpful for me and other developers too if you could please add this feature as well.

**Comment by amanshu-kataria** [comment]
@masonlouchart can I expect this feature any soon?

**Comment by masonlouchart** [comment]
@amanshu-kataria I'm not an official maintainer. You can use the native `setTimeout` function refresh your HTML element at the frequency you want.

**Comment by amanshu-kataria** [comment]
I'm already using it. I'm afraid that it may cause performance issues to the browser as it'll be never ending process. If there's any other efficient way then please let me know. It'll be really very helpful.

________________________________

**Comment by saeidzebardast** [comment]
I'll check it this weekend.

**Comment by saeidzebardast** [comment]
`moment-js` component is just a wrapper for `momentjs` library. If you want an additional feature, e.g. `auto-update`, you need to write some code.
btw, you could implement a simple component for `auto-update` feature.
