### ISSUE TITLE
[Feature request] Setting the element to return a locale date format

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#3]
For now I think it's not possible to get the locale date. Moreover, the `moment` instance is not exposed.

It could be just a boolean to say "use the navigator locale":

``` html
<moment-js format="YYYY-MM-DD HH:mm:ss" locale></moment-js>
```

or it could take a value to set the locale to use:

``` html
<moment-js format="YYYY-MM-DD HH:mm:ss" locale="fr-FR"></moment-js>
```

Please tell me if I missed something. Like @ArthurJahn said in an other issue, maybe we could...

>  add global configs to moment by passing `attrs` values to your component, like
>  <moment-js global-locale="pt-br"></moment-js>

**Comment by masonlouchart** [comment]
I already worked on that feature but the issue #1 has to be fixed before. The reason is, a new import of `momentjs` will reset the global settings. Moreover, @ArthurJahn already started a work and it's really good. I would like add the feature with the new structure.

**Comment by Boscop** [comment]
Any progress on this? #1 seems to be fixed now.

I need to display the weekday in the browser's locale (or be able to specify a locale other than English).

**Comment by masonlouchart** [comment]
Hi @Boscop ! I'll take a look asap. Maybe this weekend.

**Comment by Boscop** [comment]
Thanks :)

**Comment by masonlouchart** [comment]
Please see (and review) the PR #31.
