### ISSUE TITLE
[feature request] attribute "auto" for live reloading

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#33]
@saeidzebardast said in the issue #29 

> `moment-js` component is just a wrapper...you could implement a simple component for auto-update feature.

IMHO, this feature is useful and could be nice to have. Except if the purpose is really just to be a wrapper of `momentjs` library and extra features are prohibited, I could to make a PR for this one.

**Comment by saeidzebardast** [comment]
@masonlouchart I think it's better to still have this component, `moment-js`, as a wrapper without any extra features. But you could create another Polymer element on top of `moment-js` with extra features. e.g. `moment-js-full` or `moment-js-auto`.
