### ISSUE TITLE
The unit tests test nothing

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#35]
I found our unit tests suites are inefficient. They assert on _"moment-is-ready"_ event without "calling properly `done`" at the end, so they all pass without being executed.

Only the test [at line 50](https://github.com/saeidzebardast/moment-js/blob/master/test/basic-test.html#L50) is good because it defines the `done` parameter.

To check what I mean it's simple. Add `console.log` after assertions and run tests with option `-p`.
Run `polymer test -l chrome -p` for example. Open the console and see there is no logs.

By adding the `done` parameter (like at the line 50) they all fail because of timeout (excepted the first one but it is the only good and was already passing).

**Comment by masonlouchart** [comment]
Maybe this picture is more explicit. `moment-is-ready` event fired only once for all unit tests suite.

<img width="522" alt="capture d ecran 2017-12-23 a 01 01 39" src="https://user-images.githubusercontent.com/2325091/34315194-e8ba1004-e77c-11e7-9011-3c15e9a98d9d.png">

**Comment by saeidzebardast** [comment]
A simple solution is to add `done` parameter and following lines after `addEventLoistener(){}`:

```javascript
      if (window.moment) {
        myEl.fire('moment-is-ready');
      }
```

**Comment by saeidzebardast** [comment]
<img width="553" alt="screen shot 2017-12-23 at 10 50 15" src="https://user-images.githubusercontent.com/896271/34318702-24ff9e74-e7cf-11e7-8539-cf13ca8818d3.png">
