### ISSUE TITLE
Migrate to Polymer 3

### ISSUE THREAD

**Issue by RoXuS** [saeidzebardast/moment-js#38]
Hello !

We use it our component since 2016 (thx) and we want migrate to Polymer 3.

Did you plan to migrate on it?
Would you accept a PR from me about this?

**Comment by saeidzebardast** [comment]
Hello @RoXuS ,

That would be great if you do the migration to Polymer 3. Please let me know when your PR was ready.

**Comment by masonlouchart** [comment]
Since Polymer 3 is using ES modules, I'm not sure it's useful to wrap an API originally written in JavaScript into an HTML one to use it in JS file.

**Comment by saeidzebardast** [comment]
@masonlouchart I agree.
