### ISSUE TITLE
[Proposal] Surround the content by a span

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#4]
I would like surround the content by a span tag to avoid useless whitespaces.

<img width="356" alt="moment-js content with useless whitespaces" src="https://cloud.githubusercontent.com/assets/2325091/16171597/216dc610-3573-11e6-9fe1-42df49a7b94e.png">

**Comment by masonlouchart** [comment]
With the PR:

<img width="308" alt="capture d ecran 2016-06-18 a 17 10 16" src="https://cloud.githubusercontent.com/assets/2325091/16171750/9768d3f6-3577-11e6-9b71-24d84eb4f9e7.png">

**Comment by masonlouchart** [comment]
I thought remove the dom-if template, what do you think ? What the difference at a "performance" viewpoint ?

### diff

``` diff
<template>
-   <template is="dom-if" if="[[!hide]]">
-     <span>[[formattedDate]]</span>
-   </template>
+   <span hidden$="[[hide]]">[[formattedDate]]</span>
</template>
```

### result

<img width="1652" alt="capture d ecran 2016-06-18 a 17 13 48" src="https://cloud.githubusercontent.com/assets/2325091/16171793/ff9dedf2-3578-11e6-8111-25714d3dfcda.png">

**Comment by saeidzebardast** [comment]
Thanks for the suggestion. I think we could use the `span` with `hidden` property in this case. It's clearer to use it. Could you update your PR #5 ?

**Comment by masonlouchart** [comment]
Sure. The commit was already ready to be pushed ! 📦  (and it's done)
