### ISSUE TITLE
Define momentjs as a peer dependency

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#7]
I suggest to define the `momentjs` library as a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) because it could be used directly by the client into a computed property for exemple, to fill an input field. It would be nice to let the user and the other components use the same version of our dependency.

What do you think about it ?

**Comment by saeidzebardast** [comment]
Polymer uses Bower for dependency management. Bower does not support peer dependency. If any conflict occurred, the developer will choose the version of the library.

**Comment by masonlouchart** [comment]
I didn't know Bower doesn't support peer dependencies. Thanks!
