### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by masonlouchart** [saeidzebardast/moment-js#8]
I don't find the documentation for the `formattedDate` explicit. It should be specified that's an upward readonly property.

Also, what about to use the dashed attributes notation? I mean use `formatted-date="{value}"` instead of `formatteddate="{value}"`.

**Comment by masonlouchart** [comment]
If you simply turn the property readonly you can't set the value into the [_updateFormattedDate](https://github.com/saeidzebardast/moment-js/blob/master/moment-js.html#L115) method. The unit test are failing.

When I said

> It should be specified that's an upward readonly property.

I meant it shouldn't be writable by the consumer of `moment-js` element. I don't know how to do that. Meanwhile, I guess the new documentation could be enough to alert the developers.

**Comment by saeidzebardast** [comment]
Thanks @LM450N. I've fixed the setter.
